In [14]:
import pandas as pd

df_pot = pd.read_excel(r"D:\tg\dados\planilhas\active_power_solar_field.xlsx", sheet_name="Inverter_796")

df_pot.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54066 entries, 0 to 54065
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   tempo     54066 non-null  object
 1   Beberibe  54066 non-null  float64
dtypes: float64(1), object(1)
memory usage: 844.9+ KB

In [15]:
df_pot['tempo'] = pd.to_datetime(df_pot['tempo'], format='%Y-%m-%d %H:%M:%S')

df_pot.describe()

                               tempo      Beberibe
count                          54066  54066.000000
mean   2025-10-11 03:02:58.492952832   1384.232807
min              2025-03-06 10:45:00      0.000000
25%              2025-07-03 08:36:15    572.198441
50%              2025-10-10 10:37:30   1678.617140
75%              2026-01-18 09:48:45   2161.006248
max              2026-05-15 17:35:00   2503.648725
std                              NaN    829.051808

In [16]:
df_pot.head()

                tempo     Beberibe
0 2025-03-06 10:45:00  2392.109847
1 2025-03-06 10:50:00  2457.443291
2 2025-03-06 10:55:00  2409.572066
3 2025-03-06 11:00:00  2157.036063
4 2025-03-06 11:05:00  2288.638895

In [17]:
# Localiza no fuso UTC-3 e converte para timestamp Unix (segundos)
df_pot['timestamp'] = df_pot['tempo'].dt.tz_localize('America/Fortaleza').astype('int64') // 10**9

df_pot.head()

                tempo     Beberibe   timestamp
0 2025-03-06 10:45:00  2392.109847  1741268700
1 2025-03-06 10:50:00  2457.443291  1741269000
2 2025-03-06 10:55:00  2409.572066  1741269300
3 2025-03-06 11:00:00  2157.036063  1741269600
4 2025-03-06 11:05:00  2288.638895  1741269900

In [18]:
df_temp_solar_field = pd.read_excel(r"D:\tg\dados\planilhas\ambient_temperature_solar_field.xlsx", sheet_name="Inverter_796")

df_temp_solar_field['tempo'] = pd.to_datetime(df_temp_solar_field['tempo'], format='%Y-%m-%d %H:%M:%S')

display(df_temp_solar_field.head())

display(df_temp_solar_field.describe())

                tempo   Beberibe
0 2025-03-06 10:45:00  30.912462
1 2025-03-06 10:50:00  31.092664
2 2025-03-06 10:55:00  31.413408
3 2025-03-06 11:00:00  31.635397
4 2025-03-06 11:05:00  31.689926

                               tempo      Beberibe
count                          41239  41239.000000
mean   2025-08-25 16:11:12.433861120     29.061911
min              2025-03-06 10:45:00     17.527951
25%              2025-06-10 09:32:30     27.671396
50%              2025-08-27 06:25:00     29.688796
75%              2025-11-09 09:17:30     30.948238
max              2026-02-05 06:55:00     35.133957
std                              NaN      2.519621

In [19]:
df_h_irrad = pd.read_excel(r"D:\tg\dados\planilhas\horizontal_irradiance_meteo.xlsx", sheet_name="Inverter_798")

df_h_irrad['tempo'] = pd.to_datetime(df_h_irrad['tempo'], format='%Y-%m-%d %H:%M:%S')

display(df_h_irrad.head())

display(df_h_irrad.describe())

                tempo  Meteo - Beberibe
0 2025-03-01 00:05:00         -1.412596
1 2025-03-01 00:10:00         -1.117455
2 2025-03-01 00:15:00         -0.710776
3 2025-03-01 00:20:00         -0.293162
4 2025-03-01 00:25:00         -0.040432

                               tempo  Meteo - Beberibe
count                         102773     102773.000000
mean   2025-10-11 05:26:48.191840256         17.358935
min              2025-03-01 00:05:00       -996.000000
25%              2025-07-03 08:15:00         -3.548359
50%              2025-10-11 02:55:00         -1.671521
75%              2026-01-18 02:45:00        399.976773
max              2026-05-15 20:25:00       1279.460800
std                              NaN        596.062710

In [20]:
df_humid = pd.read_excel(r"D:\tg\dados\planilhas\humidity.xlsx", sheet_name="Inverter_798")
df_humid['tempo'] = pd.to_datetime(df_humid['tempo'], format='%Y-%m-%d %H:%M:%S')

display(df_humid.head())

display(df_humid.describe())

                tempo  Meteo - Beberibe
0 2025-03-01 00:05:00         95.563340
1 2025-03-01 00:10:00         95.567858
2 2025-03-01 00:15:00         95.749968
3 2025-03-01 00:20:00         95.749046
4 2025-03-01 00:25:00         95.745150

                               tempo  Meteo - Beberibe
count                         102773     102773.000000
mean   2025-10-11 05:26:48.191840256       -147.026066
min              2025-03-01 00:05:00       -999.000000
25%              2025-07-03 08:15:00         51.077679
50%              2025-10-11 02:55:00         70.580032
75%              2026-01-18 02:45:00         81.913457
max              2026-05-15 20:25:00         99.839548
std                              NaN        433.821838